

class RadioData
{
  String imgeurl;
  String title;
  String description;
RadioData({this.imgeurl,this.title,this.description});
}
const String   decript=   "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.";

List<RadioData> audio(){
  List myaudio = <RadioData>[
    RadioData(title: "Non Stop Radio",description:"Mpire Non Stop Radio speelt hits van toen, nu én de toekomst! Dagelijkse zorgvuldig samengestelde playlists hoor je op Mpire Radio. Uiteraard enkel met de vetste tracks van eigen bodem!Luister elke nacht van 00:00-06:00u naar NON STOP NIGHT.Luister elke dag van 10:00-11:00u, 13:00-15:00u, 16:00-17:00u en 19:00-21:00u naar MPIRE NON STOP RADIO.Enjoy!", imgeurl: "assets/images/radiopics/Pic1.PNG"),
    RadioData(title: "Early Birds",description: "Goedemorgen, luisteraars! Word rustig wakker met Early Birds op Mpire Radio!Fantastische softhits, acoustics en vrolijke songs om je dag positief te starten. Uiteraard alleen songs van eigen bodem, zoals je gewend bent van Mpire Radio. Tune in van maandag t/m zaterdag van 06:00-09:00u op Mpire Radio.",imgeurl: "assets/images/radiopics/Pic2.PNG"),
    RadioData(title: "Foute Boel",description: "Dames en heren, welkom bij Foute Boel met Piet Boel!Luister naar Mpire Radio van maandag t/m zaterdag van 09:00-10:00u voor hét foute uurtje waarvan je niet wist dat je eraan toe was!Piet Boel zit klaar om de lekkerste foute hits van eigen bodem met jou door te nemen! Mis het niet.",imgeurl: "assets/images/radiopics/Pic3.PNG"),
    RadioData(title: "Hitscout",description: "Mpire Radio is ook hét nieuwste platform voor upcoming artists, bands, songwriters en projecten!De nieuwste hits hoor je bij Hitscout.Ben jij een manager of artiest? Zend dan nu jouw nieuwste single in via www.hitscout.nl Je kunt je hier ook aanmelden voor ons online magazine! Iedere dag tussen 12:00-13:00u hoor je de Hitscout Top 5 en andere nieuwe songs met hitpotentie!",imgeurl: "assets/images/radiopics/Pic4.png"),
    RadioData(title: "Mpire Top 40",description: "De Top 40 van Mpire Radio. Uiteraard enkel met hits van eigen bodem. Zorgvuldig samengesteld door het A&R Team van Mpire Radio. Wekelijks een nieuwe top 40! Onze Top 40 Lijst is ook te vinden op Spotify!Tune iedere dag van 15:00-17:00u in op Mpire Radio.",imgeurl: "assets/images/radiopics/Pic5.png"),
    RadioData(title: "Ready to Rock",description: "De beste Rock van NL! Iedere maandag van 22:00-23:00u op Mpire Radio!",imgeurl: "assets/images/radiopics/Pic6.png"),
    RadioData(title: "Yes to Soul & Jazz",description: "Omdat Nederland niet alleen maar vol zit met volksliederen, popsongs maar ook de vetste soul & jazz maakt, Say Yes To Soul & Jazz! Iedere woensdag van 22:00-23:00u op Mpire Radio!",imgeurl: "assets/images/radiopics/Pic7.png"),
    RadioData(title: "Dance Dinsdag",description: "Het is geen geheim dat Nederland het geboorteland is van de grootste DJ’s ter wereld! Op dinsdag is het Dance Dinsdag bij Mpire Radio! Iedere dinsdag van 22:00-23:00u zijn de beste Dance Tracks te horen!",imgeurl: "assets/images/radiopics/Pic8.PNG"),
    RadioData(title: "Unwind",description: "Heerlijk, net klaar met je werk, onderweg naar huis, misschien al rustig aan het koken… De Unwind Playlist sluit hier perfect op aan! Met deze songs kun je even lekker unwinden. Wederom enkel songs met Nederlandse Roots! Relax van maandag t/m zaterdag van 18:00-19:00u met Mpire Radio.",imgeurl: "assets/images/radiopics/Pic9.png"),
    RadioData(title: "Hollands Uurtje",description: "Eerlijk is eerlijk, Nederland zou Nederland niet zijn zonder de Hollandse volksliederen. En Mpire Radio zou niet geloofwaardig zijn als radiostation met songs van eigen bodem als we geen heel uur opdragen aan precies dit genre! Zing mee met de klassiekers en laat je meevoeren door de nieuwste hits. Iedere donderdag van 22:00-23:00u bij Mpre Radio!",imgeurl: "assets/images/radiopics/Pic10.png"),
    RadioData(title: "Latin Lovers",description: "Ai, ai, ai, het uurtje om lekker te dansen op je favoriete songs met latinvibes. Ben jij een Latin Lover? Luister iedere zaterdag van 22:00-23:00u naar Mpire Radio!",imgeurl: "assets/images/radiopics/Pic11.png"),
    RadioData(title: "Topgig",description: "Bij Topgig luister je iedere zondag tussen 22:00-23:00u naar live uitzendingen van evenementen of artiesten!",imgeurl: "assets/images/radiopics/Pic12.png"),
    RadioData(title: "Party `n Go",description: "Feestje bouwen? De lekkerste party hits hoor je maar liefst iedere avond tussen 23:00-00:00u! Maak van iedere dag een feestje bij Mpire Radio!",imgeurl: "assets/images/radiopics/Pic13.png"),
    RadioData(title: "Urban Hour",description: "Bij Urban Hour hoor je de vetste rap, R&B en urban tracks van dit moment! Allemaal van eigen bodem! Luister iedere vrijdag van 22:00-23:00u naar Mpire Radio!",imgeurl: "assets/images/radiopics/Pic14.png"),


  ];
  return myaudio;
}
